### ISSUE TITLE
`nps init` should import scripts that work exactly as they do in npm run.

### ISSUE THREAD

**Issue by benmonro** [kentcdodds/nps#108]
`npm init` script should import scripts from package.json so that they work the same under p-s.

i.e. if I run `nps init` on the following package.json

```json
scripts:{
  "prething": "echo pre-thing",
   "thing":"echo thing"
}
```

then I should get the following output (in yaml)
```yaml
scripts:
    prething: 
        default: echo pre-thing
    thing: 
         default: nps prething && echo thing
```
