### ISSUE TITLE
init command fails with a null path TypeError

### ISSUE THREAD

**Issue by wopian** [kentcdodds/nps#124]
- `nps` version: 5.0.4
- `node` version: 7.2.1
- `npm` version: 4.1.2

`package.json`:

```json
"scripts": {
    "dev": "node build/dev-server.js",
    "build": "node build/build.js",
    "test": "cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run",
    "lint": "eslint --ext .js,.vue client test/unit/specs"
  },
```

The command executed:

```console
./node_modules/.bin/nps init --type yml
```

The output:

```console
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:186:7)
    at Function.module.exports.sync (C:\github\hibari\node_modules\locate-path\index.js:20:28)
    at Function.module.exports.sync (C:\github\hibari\node_modules\nps\node_modules\find-up\index.js:38:27)
    at Object.onInit [as handler] (C:\github\hibari\node_modules\nps\dist\bin-utils\parser.js:155:49)
    at Object.self.runCommand (C:\github\hibari\node_modules\nps\node_modules\yargs\lib\command.js:170:22)
    at parseArgs (C:\github\hibari\node_modules\nps\node_modules\yargs\yargs.js:920:28)
    at Object.Yargs.self.parse (C:\github\hibari\node_modules\nps\node_modules\yargs\yargs.js:499:18)
    at parse (C:\github\hibari\node_modules\nps\dist\bin-utils\parser.js:85:27)
    at Object.<anonymous> (C:\github\hibari\node_modules\nps\dist\bin\nps.js:22:33)
```

Problem description:

Running the initialisation script to generate and update package.json automatically fails with the above error with the 4 scripts I currently have.

[Repo](https://github.com/wopian/hibari)

**Comment by kentcdodds** [comment]
Thanks for the report. I'll get to it when I can. Anyone wanna dig in a bit?

**Comment by wopian** [comment]
Further note: windows 10 and with VSCode 1.10's terminal.

Same scripts written in `package-scripts.yml` function just fine with `"start": "nps"` in `package.json`:

```yml
scripts:
  dev:
    script: node build/dev-server.js
    description: run server and watch for changes
  build:
    default:
      script: node build/build.js
      description: build from source code
    report:
      script: node build/build.js --report
      description: build from source code & generate a report on file size
  test:
    script: cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run
    description: run tests with karma
  lint:
    script: eslint --ext .js,.vue client test/unit/specs
    description: lint files with eslint

```
